### ISSUE TITLE
Having some issues with the Windows version

### ISSUE THREAD

**Issue by YvonneLiLi** [XiaoLi332/OsSwitcher#1]
Great work! The tool works perfectly for switching between Linux systems. However, I’m experiencing an issue on Windows: when I click on OsSwitcher.bat, it immediately crashes and closes. Do you know how I can resolve this problem?

**Comment by XiaoLi332** [comment]
Thank you for your feedback! I'm glad to hear that the tool is working well for Linux systems.
The issue is likely due to line endings from temp.txt. Instead of renaming temp.txt to OsSwitcher.bat, try creating a new .bat file in Windows and pasting the content into it. This ensures proper Windows formatting and avoids compatibility issues. Alternatively, convert line endings using a tool like Notepad++ or unix2dos. Let me know if this helps!

**Comment by YvonneLiLi** [comment]
Your solution fixed it perfectly, much appreciated!
